# SmartThings Host Pinger
smartthings_ide: "https://graph-na04-useast2.api.smartthings.com"
host_pinger_access_token: ""
host_pinger_app_id: ""
orbi_password: ''

# Host Rules
rules:
  "DEREK":
    field: name
    pattern: "^DEREK:"
